version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  commands:
    - cd doc
    - pwd
    - cmake .
    - cmake --build . --target doxygen
    - mkdir --parents $READTHEDOCS_OUTPUT/html/
    - cp --recursive html/* $READTHEDOCS_OUTPUT/html/
