name: Build
on: [pull_request, workflow_dispatch]
jobs:
  x64-linux-dynamic:
    runs-on: ubuntu-22.04
    timeout-minutes: 150
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ./build.sh
        env:
          ghcr_login: ${{ github.actor }}
          ghcr_password: ${{ github.token }}
      - uses: actions/upload-artifact@v2
        with:
          name: x64-linux-dynamic
          path: |
            ./*.bz2
            ./*.sha1
          if-no-files-found: error
  x64-windows:
    runs-on: windows-2019
    timeout-minutes: 150
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run:
          ./build.ps1
        env:
          ghcr_login: ${{ github.actor }}
          ghcr_password: ${{ github.token }}
      - uses: actions/upload-artifact@v2
        with:
          name: x64-windows
          path: |
            ./*.zip
            ./*.sha1
          if-no-files-found: error
  x64-osx-dynamic:
    runs-on: macos-12
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run:
          ./build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: x64-osx-dynamic
          path: |
            ./*.bz2
            ./*.sha1
          if-no-files-found: error
