name: Build
on: [pull_request, workflow_dispatch]
jobs:
  build_x86_64_linux:
    runs-on: ubuntu-22.04
    timeout-minutes: 150
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ./build.sh --release
        env:
          ghcr_login: ${{ github.actor }}
          ghcr_password: ${{ github.token }}
      - uses: actions/upload-artifact@v2
        with:
          name: x86_64_linux_build
          path: |
            ./*.bz2
            ./*.sha1
          if-no-files-found: error
  build_msvc:
    runs-on: windows-2019
    timeout-minutes: 150
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run:
          ./build_in_docker.ps1
        env:
          ghcr_login: ${{ github.actor }}
          ghcr_password: ${{ github.token }}
      - uses: actions/upload-artifact@v2
        with:
          name: msvc_build
          path: |
            ./*.zip
            ./*.sha1
          if-no-files-found: error
  build_debug_msvc:
    runs-on: windows-2019
    timeout-minutes: 150
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run:
          ./build_in_docker.ps1 Debug
        env:
          ghcr_login: ${{ github.actor }}
          ghcr_password: ${{ github.token }}
      - uses: actions/upload-artifact@v2
        with:
          name: msvc_debug_build
          path: |
            ./*.zip
            ./*.sha1
          if-no-files-found: error
  build_osx:
    runs-on: macos-12
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run:
          ./build.sh --release
      - uses: actions/upload-artifact@v2
        with:
          name: osx_build
          path: |
            ./*.bz2
            ./*.sha1
          if-no-files-found: error
