name: Build
on: [pull_request, workflow_dispatch]
jobs:
  x64-linux-dynamic:
    runs-on: ubuntu-22.04
    timeout-minutes: 150
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache/restore@v3
        with:
          path: ~/.cache/vcpkg/archives
          key: vcpkg-binary-cache-x64-linux-dynamic-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
          restore-keys: |
            vcpkg-binary-cache-x64-linux-dynamic
      - run: ./build.sh
        env:
          ghcr_login: ${{ github.actor }}
          ghcr_password: ${{ github.token }}
      - uses: actions/cache/save@v3
        if: always()
        with:
          path: ~/.cache/vcpkg/archives
          key: vcpkg-binary-cache-x64-linux-dynamic-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: actions/upload-artifact@v2
        with:
          name: x64-linux-dynamic
          path: |
            ./*.bz2
            ./*.sha1
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: x64-linux-dynamic-buildtree
          path: vcpkg/buildtrees/doctotext
          if-no-files-found: error
  x64-windows:
    runs-on: windows-2019
    timeout-minutes: 150
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache/restore@v3
        with:
          path: ~\AppData\Local\vcpkg\archives
          key: vcpkg-binary-cache-x64-windows-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
          restore-keys: |
            vcpkg-binary-cache-x64-windows
      - run:
          ./build.ps1
        env:
          ghcr_login: ${{ github.actor }}
          ghcr_password: ${{ github.token }}
      - uses: actions/cache/save@v3
        if: always()
        with:
          path: ~\AppData\Local\vcpkg\archives
          key: vcpkg-binary-cache-x64-windows-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: actions/upload-artifact@v2
        with:
          name: x64-windows
          path: |
            ./*.zip
            ./*.sha1
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: x64-windows-buildtree
          path: vcpkg/buildtrees/doctotext
          if-no-files-found: error
  x64-osx-dynamic:
    runs-on: macos-12
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache/restore@v3
        with:
          path: ~/.cache/vcpkg/archives
          key: vcpkg-binary-cache-x64-osx-dynamic-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
          restore-keys: |
            vcpkg-binary-cache-x64-osx-dynamic
      - run:
          ./build.sh
      - uses: actions/cache/save@v3
        if: always()
        with:
          path: ~/.cache/vcpkg/archives
          key: vcpkg-binary-cache-x64-osx-dynamic-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: actions/upload-artifact@v2
        with:
          name: x64-osx-dynamic
          path: |
            ./*.bz2
            ./*.sha1
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: x64-osx-dynamic-buildtree
          path: vcpkg/buildtrees/doctotext
          if-no-files-found: error
